[package]
name = "integration-tests-fastauth"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-process = "1"
bollard = "0.13"
clap = { version = "4.2", features = ["derive", "env"] }
futures = "0.3"
hex = "0.4.3"
hyper = { version = "0.14", features = ["full"] }
once_cell = "1"
rand = "0.7"
serde = "1"
serde_json = "1"
testcontainers = { version = "0.15", features = ["experimental"] }
tokio = { version = "1.28", features = ["full"] }
toml = "0.8.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# crypto dependencies
aes-gcm = "0.10"
curv = { package = "curv-kzen", version = "0.9", default-features = false }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
multi-party-eddsa = { git = "https://github.com/DavidM-D/multi-party-eddsa.git", rev = "25ae4fdc5ff7819ae70e73ab4afacf1c24fc4da1" }

# near dependencies
near-crypto = "0.17.0"
near-fetch = "0.0.12"
near-primitives = "0.17.0"
near-workspaces = { git = "https://github.com/near/near-workspaces-rs.git", rev = "97d644983c0302b737e7d0787b554b5e7efe420a" }

# local dependencies
mpc-recovery = { path = "../../mpc-recovery" }

[dev-dependencies]
test-log = { version = "0.2.12", features = ["log", "trace"] }


[workspace] # used to ignore higher level workspace

[features]
default = []
docker-test = []
flamegraph = ["mpc-recovery/disable-open-telemetry"]
